workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.ahernandez.financeapp"
        APP_NAME: "Finance App"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: development
        bundle_identifier: com.ahernandez.financeapp
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      
      - name: Set up code signing with Apple credentials
        script: |
          # Configurar keychain
          keychain initialize
          
          # Usar las credenciales para generar certificados
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
          
          # Aplicar los perfiles
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - ahernandez429@soyudemedellin.edu.co
        notify:
          success: true
          failure: true

  # Workflow alternativo para generar IPA (requiere certificados de Apple)
  ios-release-workflow:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.tuempresa.financeapp"
        APP_NAME: "Finance App"
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build IPA
        script: |
          flutter build ipa --release
        # Esto fallará sin certificados de firma, pero puedes configurarlos después
        ignore_failure: true
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    
    publishing:
      email:
        recipients:
          - ahernandez429@soyudemedellin.edu.co
        notify:
          success: true
          failure: true
