workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.ahernandez.financeapp"
        APP_NAME: "Finance App"
        # Variables para firma de código
        # Debes agregar estas en Codemagic UI:
        # APPLE_ID: tu email de Apple
        # APP_SPECIFIC_PASSWORD: irqa-yzvy-yjxh-pigz
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      
      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true
      
      - name: Build iOS IPA with automatic code signing
        script: |
          # Configurar firma automática
          xcode-project use-profiles
          
          # Build IPA
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
        ignore_failure: false
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - ahernandez429@soyudemedellin.edu.co
        notify:
          success: true
          failure: true

  # Workflow alternativo para generar IPA (requiere certificados de Apple)
  ios-release-workflow:
    name: iOS Release Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.tuempresa.financeapp"
        APP_NAME: "Finance App"
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build IPA
        script: |
          flutter build ipa --release
        # Esto fallará sin certificados de firma, pero puedes configurarlos después
        ignore_failure: true
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    
    publishing:
      email:
        recipients:
          - ahernandez429@soyudemedellin.edu.co
        notify:
          success: true
          failure: true
